# -*- coding: utf-8 -*-
"""slicer-func.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1secJSK-H8W0-96jvHRkvrVj3qeqVXe2A
"""

def custom_slicer(input_list, start, end, step):
    return input_list[start:end:step]

list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]
    ]
]

# Accessing element
element = list_3d[1][2][0]  # Accesses 16 from the 3D list
print(element)